### ISSUE TITLE
Globs

### ISSUE THREAD

**Issue by svrc** [cf-platform-eng/nsx-ci-pipeline#2]
seeing Concourse 3.2 and 3.3 erroring on the globs here:
https://github.com/cf-platform-eng/nsx-ci-pipeline/blame/master/pipelines/new-setup-with-nsx-edge-gen-iso-segment/pipeline.yml#L239

this is fixed if we move the **globs:** into a **params:** list ; not sure if this is a concourse issue or just something they've changed in recent versions that needs to be updated in the pipelines.

```
unknown/extra keys:
  - jobs[2].plan[0].aggregate[2].globs
  - jobs[3].plan[0].aggregate[1].globs
  - jobs[4].plan[0].aggregate[1].globs
  - jobs[5].plan[0].aggregate[2].globs
  - jobs[6].plan[0].aggregate[1].globs
  - jobs[7].plan[0].aggregate[1].globs
  - jobs[9].plan[0].aggregate[1].globs
  - jobs[10].plan[0].aggregate[1].globs

```

**Comment by sparameswaran** [comment]
Fixed the om-cli to have a params parent of glob introduced by concourse changes in 3.x. Please check against master and let me know if its unresolved. Thanks.

**Comment by svrc** [comment]
0bdbf13d8597bc9a2de6aac195438a2232738df7 looks like it does the trick.  Thanks, and on your vacation no less!  Would have PRd this but wanted to confirm with you...
